<a href="https://colab.research.google.com/github/Pragati-cloud/PythonBasic/blob/main/Embedding_Practice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

docs = ['hello india','yesterday indian cricket team win world cup','it is very proud moment for india','let cheers for indian team','cheers for india','jemimah , radha , richa , deepti played very well']

In [3]:

from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='<nothing>')

In [4]:
tokenizer.fit_on_texts(docs)

In [5]:
tokenizer.word_index

{'<nothing>': 1,
 'india': 2,
 'for': 3,
 'indian': 4,
 'team': 5,
 'very': 6,
 'cheers': 7,
 'hello': 8,
 'yesterday': 9,
 'cricket': 10,
 'win': 11,
 'world': 12,
 'cup': 13,
 'it': 14,
 'is': 15,
 'proud': 16,
 'moment': 17,
 'let': 18,
 'jemimah': 19,
 'radha': 20,
 'richa': 21,
 'deepti': 22,
 'played': 23,
 'well': 24}

In [6]:
tokenizer.word_counts

OrderedDict([('hello', 1),
             ('india', 3),
             ('yesterday', 1),
             ('indian', 2),
             ('cricket', 1),
             ('team', 2),
             ('win', 1),
             ('world', 1),
             ('cup', 1),
             ('it', 1),
             ('is', 1),
             ('very', 2),
             ('proud', 1),
             ('moment', 1),
             ('for', 3),
             ('let', 1),
             ('cheers', 2),
             ('jemimah', 1),
             ('radha', 1),
             ('richa', 1),
             ('deepti', 1),
             ('played', 1),
             ('well', 1)])

In [7]:
tokenizer.document_count

6

In [8]:
sequence = tokenizer.texts_to_sequences(docs)
sequence

[[8, 2],
 [9, 4, 10, 5, 11, 12, 13],
 [14, 15, 6, 16, 17, 3, 2],
 [18, 7, 3, 4, 5],
 [7, 3, 2],
 [19, 20, 21, 22, 23, 6, 24]]

In [9]:
from keras.utils import pad_sequences

In [16]:
sequence = pad_sequences(sequence,padding='post')
sequence

array([[ 8,  2,  0,  0,  0,  0,  0],
       [ 9,  4, 10,  5, 11, 12, 13],
       [14, 15,  6, 16, 17,  3,  2],
       [18,  7,  3,  4,  5,  0,  0],
       [ 7,  3,  2,  0,  0,  0,  0],
       [19, 20, 21, 22, 23,  6, 24]], dtype=int32)

In [25]:
from keras import Sequential
from keras.layers import Dense , SimpleRNN, Embedding , Flatten

model = Sequential()
model.add(Embedding(input_dim=25, output_dim=2, input_length=7))
model.build(input_shape=(None,7))
model.summary()


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)         │ (None, 7, 2)           │            50 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 50 (200.00 B)

 Trainable params: 50 (200.00 B)

 Non-trainable params: 0 (0.00 B)

In [26]:
model.compile('adam','accuracy')

In [27]:
import numpy as np
sequence = np.array(sequence).astype('int32')
print(sequence.shape)   # it MUST print (6,7)


(6, 7)


In [28]:
pred = model.predict(sequence)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
[[[-0.03036543  0.04725433]
  [ 0.0470178  -0.0198662 ]
  [ 0.01799482  0.01149597]
  [ 0.01799482  0.01149597]
  [ 0.01799482  0.01149597]
  [ 0.01799482  0.01149597]
  [ 0.01799482  0.01149597]]

 [[-0.02569761 -0.03757123]
  [ 0.04721863  0.04436297]
  [ 0.03060216  0.00973732]
  [ 0.04616059  0.01172038]
  [-0.02229009 -0.02222384]
  [ 0.01028973 -0.04173018]
  [-0.04733496 -0.02595905]]

 [[-0.00242945 -0.03697777]
  [-0.02702883  0.04675538]
  [ 0.02350866  0.01564376]
  [-0.04354283 -0.01101762]
  [-0.04557291 -0.00872514]
  [ 0.01496902  0.01774785]
  [ 0.0470178  -0.0198662 ]]

 [[ 0.04917414  0.01496632]
  [-0.03532319 -0.004901  ]
  [ 0.01496902  0.01774785]
  [ 0.04721863  0.04436297]
  [ 0.04616059  0.01172038]
  [ 0.01799482  0.01149597]
  [ 0.01799482  0.01149597]]

 [[-0.03532319 -0.004901  ]
  [ 0.01496902  0.01774785]
  [ 0.0470178  -0.0198662 ]
  [ 0.01799482  0.01149597]
  [ 0.01799482  0.01149597]
  [ 0.01799482  0.01149597]
  