In [1]:
!pip install numpy



[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip



   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
    --------------------------------------- 0.3/12.9 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.9 MB 1.9 MB/s eta 0:00:07
   -- ------------------------------------- 0.8/12.9 MB 1.3 MB/s eta 0:00:10
   ---- ----------------------------------- 1.3/12.9 MB 1.6 MB/s eta 0:00:08
   ---- ----------------------------------- 1.6/12.9 MB 1.6 MB/s eta 0:00:08
   ----- ---------------------------------- 1.8/12.9 MB 1.5 MB/s eta 0:00:08
   ----- ---------------------------------- 1.8/12.9 MB 1.5 MB/s eta 0:00:08
   ----- ---------------------------------- 1.8/12.9 MB 1.5 MB/s eta 0:00:08
   ------ --------------------------------- 2.1/12.9 MB 1.2 MB/s eta 0:00:10
   ------ --------------------------------- 2.1/12.9 MB 1.2 MB/s eta 0:00:10
   ------ --------------------------------- 2.1/12.9 MB 1.2 MB/s eta 0:00:10
   ------- -------------------------------- 2.4/12.9 MB 894.7 kB/s eta 0:00:12
   -------

In [2]:
import numpy as np 

arr1 = np.array([1,2,3,4,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 4 5]
<class 'numpy.ndarray'>
(6,)


In [3]:
arr2= np.array([2,6,4,9,8])
arr2.reshape(1,5)

array([[2, 6, 4, 9, 8]])

In [9]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [14]:
np.ones((3,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
new1= np.eye(5)
print(new1)
print(new1.size)
print(new1.dtype)
print(new1.sort)
print(new1.itemsize)
print(new1.ndim)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
25
float64
<built-in method sort of numpy.ndarray object at 0x0000020FD17C9B30>
8
2


In [19]:
a1= np.array([10,20,30,40,50])
a2 = np.array([1,2,3,4,5])

print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)

[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]


In [20]:
a3= np.array([1,2,3,4,5])

print(np.sin(a3))
print(np.log(a3))
print(np.exp(a3))
print(np.sqrt(a3))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[1.         1.41421356 1.73205081 2.         2.23606798]


In [ ]:
#array slicing and indexing

arr = np.array([[34,5,6,3,7,3],[45,7,2,9,4,2],[7,3,2,8,6,4]])

print(arr[1:])



[[45  7  2  9  4  2]
 [ 7  3  2  8  6  4]]


In [30]:

arr = np.array([[34,5,6,3,7,3],[45,7,2,9,4,2],[7,3,2,8,6,4]])

print(arr[1:][1:])

arr[0][0]=100
print(arr)

[[7 3 2 8 6 4]]
[[100   5   6   3   7   3]
 [ 45   7   2   9   4   2]
 [  7   3   2   8   6   4]]
